using UnityEngine;

public class InputManager : MonoBehaviour
{
    private static InputManager instance;

    // 프로퍼티를 통한 게으른 초기화(Lazy Initialization)
    public static InputManager Instance
    {
        get
        {
            // 인스턴스가 비어있을 때만 실행
            if (instance == null)
            {
                // 코드로 빈 게임 오브젝트 생성
                GameObject go = new GameObject("InputManager_AutoGenerated");
                // 컴포넌트 부착 후 인스턴스에 할당
                instance = go.AddComponent<InputManager>();
                // 씬이 전환되어도 파괴되지 않도록 설정
                DontDestroyOnLoad(go);
            }
            return instance;
        }
    }

    public PlayerControls Controls { get; private set; }

    private void Awake()
    {
        // 씬에 이미 배치된 매니저가 있을 경우의 중복 생성 방지 로직
        if (instance == null)
        {
            instance = this;
            DontDestroyOnLoad(this.gameObject);
        }
        else if (instance != this)
        {
            Destroy(this.gameObject);
            return;
        }

        // Controls 데이터 할당 보장
        if (Controls == null)
        {
            Controls = new PlayerControls();
        }
    }
}